spawn-location:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
world: 'world'
server-appearance:
  prefix: '&7'
  primary-color: '&a'
  secondary-color: '&e'
  text-color: '&7'
  emoticon-color: '&e'
  ping-color: '&d&o'